# Generated by Django 6.0 on 2026-01-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='business_name',
        ),
    ]
