# Generated by Django 6.0 on 2026-01-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_partnerprofile_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='contact_person',
            field=models.CharField(default='', max_length=100, verbose_name='Người đại diện'),
        ),
    ]
