# Generated by Django 6.0 on 2026-01-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_partnerprofile_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='bank_bin',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mã BIN ngân hàng'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='bank_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã ngân hàng'),
        ),
    ]
