# Generated by Django 6.0 on 2026-01-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_partnerprofile_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('partner', 'Đối tác'), ('admin', 'Quản trị viên')], default='customer', max_length=10),
        ),
    ]
