# Generated by Django 6.0 on 2026-01-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_partnerprofile_bank_bin_partnerprofile_bank_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='bank_id',
        ),
    ]
