# Generated by Django 6.0 on 2026-02-23 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_customer_last_booking'),
        ('users', '0005_remove_partnerprofile_bank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('partner', 'Đối tác'), ('admin', 'Quản trị viên'), ('staff', 'Nhân viên')], default='customer', max_length=10),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='Nhân viên', max_length=100, verbose_name='Chức vụ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='partner.badmintoncenter', verbose_name='Trung tâm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
