# Generated by Django 6.0 on 2026-01-21 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0006_remove_booking_partner_boo_date_1ab428_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('days_of_week', models.JSONField(verbose_name='Thứ trong tuần')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('total_months', models.IntegerField(default=1, verbose_name='Số tháng đăng ký')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.court', verbose_name='Sân')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(max_length=20, unique=True, verbose_name='Mã đặt chỗ')),
                ('date', models.DateField(verbose_name='Ngày đặt sân')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('confirmed', 'Thanh toán'), ('checked_in', 'Đã nhận sân '), ('completed', 'Hoàn thành'), ('admin_cancelled', 'Hủy bởi Admin')], default='confirmed', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='partner.court', verbose_name='Sân')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('fixed_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.fixedschedule', verbose_name='Lịch cố định')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('transaction_type', models.CharField(default='Thanh toán', max_length=50, verbose_name='Loại giao dịch')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản ngân hàng')], max_length=50, verbose_name='Phương thức thanh toán')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giao dịch')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='booking.booking', verbose_name='Đặt chỗ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'status'], name='booking_boo_date_6751a5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_code'], name='booking_boo_booking_956aad_idx'),
        ),
    ]
