# Generated by Django 6.0 on 2026-01-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Thanh toán'), ('checked_in', 'Đã nhận sân '), ('completed', 'Hoàn thành'), ('admin_cancelled', 'Hủy bởi Admin')], default='confirmed', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
