# Generated by Django 6.0 on 2026-01-26 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status'),
        ('partner', '0007_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_boo_date_6751a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_boo_booking_956aad_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='partner.customer', verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='booking_group_code',
            field=models.CharField(db_index=True, default='BK-OLD-DATA', max_length=100, verbose_name='Mã nhóm đơn hàng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Đã xác nhận'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_reference',
            field=models.CharField(default='BK-OLD-DATA', max_length=100, unique=True, verbose_name='Mã bút toán (Bank Ref)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xác nhận'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('waiting_verify', 'Chờ xác nhận thanh toán'), ('confirmed', 'Thanh toán'), ('completed', 'Hoàn thành'), ('admin_cancelled', 'Hủy bởi Admin')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled', 'admin_cancelled']), _negated=True), fields=('court', 'date', 'start_time'), name='unique_booking_slot'),
        ),
    ]
