# Generated by Django 6.0 on 2026-02-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_booking_boo_date_6751a5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='group_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Mã nhóm đơn hàng'),
        ),
    ]
