# Generated by Django 6.0 on 2026-02-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_group_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='fixed_schedule',
        ),
        migrations.DeleteModel(
            name='FixedSchedule',
        ),
    ]
