# Generated by Django 6.0 on 2026-02-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_fixed_schedule_delete_fixedschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản')], default='transfer', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
