# Generated by Django 6.0 on 2026-01-13 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_user_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên tiện ích')),
                ('icon', models.ImageField(upload_to='amenities/', verbose_name='Icon')),
            ],
        ),
        migrations.CreateModel(
            name='BadmintonCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên trung tâm')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kinh độ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('open_time', models.TimeField(default='07:00', verbose_name='Giờ mở cửa')),
                ('close_time', models.TimeField(default='23:55', verbose_name='Giờ đóng cửa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, to='partner.amenity', verbose_name='Tiện ích')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='users.partnerprofile', verbose_name='Đối tác')),
            ],
        ),
        migrations.CreateModel(
            name='CenterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='center_images/', verbose_name='Hình ảnh trung tâm')),
                ('is_thumbnail', models.BooleanField(default=False, verbose_name='Ảnh đại diện')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partner.badmintoncenter', verbose_name='Trung tâm cầu lông')),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên sân')),
                ('base_price_per_hour', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá cơ bản/giờ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='partner.badmintoncenter')),
            ],
        ),
        migrations.CreateModel(
            name='FixedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Tên chủ nhóm')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='SĐT chủ nhóm')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.JSONField(verbose_name='Các thứ trong tuần (VD: [1,3,5])')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu gói')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc gói')),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.badmintoncenter')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.court')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khung giờ')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('days_of_week', models.JSONField(default=list, verbose_name='Ngày trong tuần áp dụng (0=Thứ 2, 6=Chủ nhật)')),
                ('price_per_hour', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá/giờ')),
                ('priority', models.IntegerField(default=1, verbose_name='Độ ưu tiên')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='partner.badmintoncenter')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên sản phẩm')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Tồn kho')),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.badmintoncenter')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100, verbose_name='Nhân viên bán')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.badmintoncenter')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('price_at_time', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá lúc bán')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='partner.serviceorder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.product')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày đặt sân')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('confirmed', 'Đã đặt cọc/Thanh toán'), ('checked_in', 'Đã nhận sân '), ('completed', 'Hoàn thành')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('booking_code', models.CharField(max_length=12, unique=True, verbose_name='Mã check-in')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='partner.court', verbose_name='Sân')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'status'], name='partner_boo_date_1ab428_idx'), models.Index(fields=['booking_code'], name='partner_boo_booking_14a69d_idx')],
            },
        ),
    ]
