# Generated by Django 6.0 on 2026-01-15 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='badmintoncenter',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='users.partnerprofile', verbose_name='Đối tác'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddField(
            model_name='centerimage',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partner.badmintoncenter', verbose_name='Trung tâm cầu lông'),
        ),
        migrations.AddField(
            model_name='court',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='partner.badmintoncenter'),
        ),
        migrations.AddField(
            model_name='booking',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='partner.court', verbose_name='Sân'),
        ),
        migrations.AddField(
            model_name='fixedschedule',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.badmintoncenter'),
        ),
        migrations.AddField(
            model_name='fixedschedule',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.court'),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='partner.badmintoncenter'),
        ),
        migrations.AddField(
            model_name='product',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.badmintoncenter'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.badmintoncenter'),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='partner.serviceorder'),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.product'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'status'], name='partner_boo_date_1ab428_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_code'], name='partner_boo_booking_14a69d_idx'),
        ),
    ]
