# Generated by Django 6.0 on 2026-01-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='icon',
        ),
    ]
