# Generated by Django 6.0 on 2026-01-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_remove_amenity_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badmintoncenter',
            name='type_court',
        ),
        migrations.AddField(
            model_name='court',
            name='type_court',
            field=models.CharField(choices=[('wooden', 'Sàn gỗ'), ('carpet', 'Sàn thảm')], default='wooden', max_length=20, verbose_name='Loại sân'),
        ),
    ]
