# Generated by Django 6.0 on 2026-01-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_remove_badmintoncenter_type_court_court_type_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='golden_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Kết thúc giờ vàng'),
        ),
        migrations.AddField(
            model_name='court',
            name='golden_price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Giá giờ vàng/giờ'),
        ),
        migrations.AddField(
            model_name='court',
            name='golden_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Bắt đầu giờ vàng'),
        ),
    ]
