# Generated by Django 6.0 on 2026-01-21 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_court_golden_end_time_court_golden_price_per_hour_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='partner_boo_date_1ab428_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='partner_boo_booking_14a69d_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='court',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='FixedSchedule',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
