# Generated by Django 6.0 on 2026-01-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_remove_booking_partner_boo_date_1ab428_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên khách hàng')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('total_visits', models.IntegerField(default=0, verbose_name='Tổng số lần đến')),
                ('total_spent', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng chi tiêu')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='partner.badmintoncenter')),
            ],
        ),
    ]
