# Generated by Django 6.0 on 2026-01-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_booking',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lần đặt sân gần nhất'),
        ),
    ]
