# Generated by Django 6.0 on 2026-02-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản')], default='cash', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
